---
title: "Resources"
output: 
  distill::distill_article:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<br/>


**Recommended papers - models**

- Franck C, Dunne JA, Le Maho Y, May RM, Thébaud C, Hochberg ME (2015) Fundamental ecology is fundamental. **_Trends in Ecology & Evolution_**, 30(1):9-16 (https://doi.org/10.1016/j.tree.2014.11.005)

- Grainger TN, Senthilnathan A, Ke P-J, Barbour MA, Jones NT, DeLong JP, Otto SP, O’Connor MI, Coblentz KE, Goel N, Sakarchi J, Szojka MC, Levine JM & Germain RM (2022) An Empiricist’s Guide to Using Ecological Theory. **_The American Naturalist_**, 199(1): 1-20 (https://doi.org/10.1086/717206)

**Recommended papers - time**

- Fronhofer EA, Govaert L, O'Connor MI, Schreiber, SJ. & Altermatt F (2024) The shape of density dependence and the relationship between population growth, intraspecific competition and equilibrium population density. **_Oikos_**, 2024(2): e09824 (10.1111/oik.09824)

- Rosenbaum B & Fronhofer EA (2023) Confronting population models with experimental microcosm data: from trajectory matching to state-space models. **_Ecosphere_**, 14(4):e4503 (10.1002/ecs2.4503)

- Huneman P (2019) How the Modern Synthesis Came to Ecology. **_J. Hist. Biol._**, 52(4):635-686 (10.1007/s10739-019-09570-9)

- Mallet J (2012) The struggle for existence: how the notion of carrying capacity, K, obscures the links between demography, Darwinian evolution, and speciation. **_Evol. Ecol. Res._**, 14(5):627-665

**Recommended papers - networks**

- Bascompte J (2009) Disentangling the Web of Life. **_Science_**, 325,416-419, (https://www.science.org/doi/10.1126/science.1170749)

- May RM (1972) Will a large complex system be stable? **_Nature_**, doi: [10.1038/238413a0](https://doi.org/10.1038/238413a0).
&nbsp;[**PDF**](biblio/may-1972.pdf)

- Williams RJ & Martinez ND (2000) Simple rules yield complex food webs. **_Nature_**, doi: [10.1038/35004572](https://doi.org/10.1038/35004572).
&nbsp;[**PDF**](biblio/williams-2000.pdf)

**Additional references**

- Akjouj, I., Barbier, M., Clenet, M., Hachem, W., Maïda, M., Massol, F., Najim, J. & Tran, V. C. (2024) Complex systems in ecology: a guided tour with large Lotka–Volterra models and random matrices. **_Proceedings of the Royal Society A: Mathematical, Physical and Engineering Sciences_**, 480, 20230284.

- Cohen JE & Briand F (1984) Trophic links of community foodwebs. **_PNAS_**, doi: [10.1073/pnas.81.13.4105](https://doi.org/10.1073/pnas.81.13.4105).
&nbsp;[**PDF**](biblio/cohen-1984.pdf)

- Cohen JE & Newman CM (1988) Dynamic basis of food web organization. **_Ecology_**, doi: [10.2307/1941142](https://doi.org/10.2307/1941142).
&nbsp;[**PDF**](biblio/cohen-1988.pdf)

- de Ruiter PC, Neutel A-M & Moore JC (1995) Energetics, patterns of interaction strengths, and stability in real ecosystems. **_Science_**, 269, doi: [10.1126/science.269.5228.1257](https://doi.org/10.1126/science.269.5228.1257).
&nbsp;[**PDF**](biblio/deruiter-1995.pdf)

- Dunne JA, Williams RJ & Martinez ND (2002) Network structure and biodiversity loss in food webs: robustness increases with connectance. **_Ecology Letters_**, doi: [10.1046/j.1461-0248.2002.00354.x](https://doi.org/10.1046/j.1461-0248.2002.00354.x).
&nbsp;[**PDF**](biblio/dunne-2002.pdf)

- Grainger TN _et al._ (2022) An empiricist’s guide to using ecological theory. **_The American Naturalist_**, doi: [10.1086/717206](https://doi.org/10.1086/717206).
&nbsp;[**PDF**](biblio/grainger-2022.pdf)

- James A _et al._ (2015) Constructing random matrices to represent real ecosystems. **_The American Naturalist_**, doi: [10.1086/680496](https://doi.org/10.1086/680496).
&nbsp;[**PDF**](biblio/james-2015.pdf)

- Leger J-B, Daudin J-J & Vacher C (2015) Clustering methods differ in their ability to detect patterns in ecological networks. **_Methods in Ecology and Evolution_**, doi: [10.1111/2041-210X.12334](https://doi.org/10.1111/2041-210X.12334).
&nbsp;[**PDF**](biblio/leger-2015.pdf)

- Lewinsohn TM _et al._ (2006) Structure in plant-animal interaction assemblages. **_Oikos_**, doi: [10.1111/j.0030-1299.2006.14583.x](https://doi.org/10.1111/j.0030-1299.2006.14583.x).
&nbsp;[**PDF**](biblio/lewinsohn-2006.pdf)

- Newman MEJ (2006) Modularity and community structure in networks. **_PNAS_**, doi: [10.1073/pnas.0601602103](https://doi.org/10.1073/pnas.0601602103).
&nbsp;[**PDF**](biblio/newman-2006.pdf)

- Podani J & Schmera D (2012) A comparative evaluation of pairwise nestedness measures. **_Ecography_**, doi: [10.1111/j.1600-0587.2011.07319.x](https://doi.org/10.1111/j.1600-0587.2011.07319.x).
&nbsp;[**PDF**](biblio/podani-2012.pdf)

- Strona G _et al._ (2014) A fast and unbiased procedure to randomize ecological binary matrices with fixed row and column totals. **_Nature Communications_**, doi: [10.1038/ncomms5114](https://doi.org/10.1038/ncomms5114).
&nbsp;[**PDF**](biblio/strona-2014.pdf)

- Stumpf MPH _et al._ (2012) Critical truths about power laws. **_Science_**, doi: [10.1126/science.1216142](https://doi.org/10.1126/science.1216142).
&nbsp;[**PDF**](biblio/stumpf-2012.pdf)

- Thomas M _et al._ (2015) Chapter 6 - A network-based method to detect patterns of local crop biodiversity: Validation at the species and infra-species levels. **_Advances in Ecological Research_**, doi: [10.1016/bs.aecr.2015.10.002](https://doi.org/10.1016/bs.aecr.2015.10.002).
&nbsp;[**PDF**](biblio/thomas-2015.pdf)

- Yang Z, Algesheimer R & Tessone CJ (2016) A comparative analysis of community detection algorithms on artificial networks. **_Scientific Reports_**, doi: [10.1038/srep30750](https://doi.org/10.1038/srep30750).
&nbsp;[**PDF**](biblio/yang-2016.pdf)
