---
title: "Solution: Epidemiological model"
author: "Camille Saade"
date: "17/05/2022"
output: html_document
---

# I - Data importation
```{r}
# cleaning the env:
rm(list = ls())
# loading libraries:
library(rstan) #  for the stats
library(ggplot2) # for some plots
library(coda) # diagnostic of mcmc output
library(deSolve) # to integrate ODEs
```


```{r}
## importing data
data_SIR = read.csv('Data/epidemio.csv')
head(data_SIR)

```


```{r}
# keeping only 1 replicate for the fit
repl = 2
data_stan = list(
  n = length(unique(data_SIR$time)),
  N_tot = sum(data_SIR[data_SIR$time == 0 & data_SIR$replicate == repl, c('S', 'I')]),
  t = data_SIR$time[data_SIR$replicate == repl],
  S = data_SIR$S[data_SIR$replicate == repl],
  I = data_SIR$I[data_SIR$replicate == repl]
)

```

# II - Model declaration
```{r}

SIR_model_str = '
functions{
  real[] odemodel(real t, real[] N, real[] p, real[] x_r, int[] x_i){
    // p[1]=alpha, p[2]=beta, p[3] = N_tot // we store N_tot in the third element of p (we dont need R as all elements sum to N_tot)
    real dNdt[2]; 
    dNdt[1] = - p[1]*N[1]*N[2]/p[3];
    dNdt[2] = p[1]*N[1]*N[2]/p[3] - p[2]*N[2];
    return dNdt;
  }
}

data{
  int n; // number of observations
  real N_tot; // population size
  real t[n]; // time
  real S[n]; // observations S
  real I[n]; // observations I
}

parameters{
  real<lower=0> alpha; // infection rate
  real<lower=0> beta; // recovery rate
  real<lower=0> sdev; // error term
  real<lower=0> S0sim; // initial density S
  real<lower=0> I0sim; // initial density I
}

model{
  real p[3]; // vector of parameters for the ODE
  real simval[n-1,2]; // simulated values, matrix. dim1 = time without t0, dim2 = dim_ODE = 2 (S = 1, I = 2)
  
  // priors 
  alpha ~ lognormal(-0.5,1);
  beta ~ lognormal(-0.5, 1);
  S0sim ~ normal(S[1],5000);
  I0sim ~ normal(I[1],500);
  sdev ~ gamma(2,0.1);
  
  // parameters for integrator
  p[1] = alpha;
  p[2] = beta;
  p[3] = N_tot;

  // integrate ODE
  simval = integrate_ode_rk45(odemodel, {S0sim, I0sim}, t[1], t[2:n], p, rep_array(0.0,0), rep_array(0,0));
  // likelihood
  S[1] ~ normal(S0sim, sdev);
  I[1] ~ normal(I0sim, sdev);
  for (i in 2:n){
    S[i] ~ normal(simval[i-1, 1], sdev);
    I[i] ~ normal(simval[i-1, 2], sdev);
  }
}

generated quantities{
}
'

```

```{r}
SIR_model = stan_model(model_code = SIR_model_str, auto_write = TRUE)
```

# III - Fit
```{r}
# stan options
chains = 3
options(mc.cores = chains)
iter   =  4000
warmup =  2000

# initial values for sampling 
init=rep(list(list(alpha=0.01,
                   beta=0.01,
                   sdev=1,
                   S0sim=data_stan$S[1],
                   I0sim=data_stan$I[1]
                   ))
         ,chains)


fit = sampling(SIR_model,
               data=data_stan,
               iter=iter,
               warmup=warmup,
               chains=chains,
               init=init)
```

# IV - Diagnostics
```{r}
print(fit, digits = 3)
```

```{r}
samples=As.mcmc.list(fit)
plot(samples[, c("alpha","beta")])
```

```{r}
pairs(fit, pars=c("alpha","beta"))
```

# V- posterior predictions

```{r}
ode.model = function(t,N,p){
  alpha = p$alpha
  beta = p$beta
  dS = -alpha*N[1]*N[2]/(N[1] + N[2] + N[3])
  dI = alpha*N[1]*N[2]/(N[1] + N[2] + N[3]) - beta*N[2]
  dR = beta*N[2]
  return(list(c(dS, dI, dR)))
}

posteriors = as.matrix(fit)

n_post = 1000
times = seq(min(data_SIR$time), max(data_SIR$time), length.out = 200)
N_tot = data_stan$N_tot
for (k in 1:n_post){
  par = posteriors[sample(1:nrow(posteriors), 1),]
  sim = ode(c(par['S0sim'], par['I0sim'], N_tot - par['S0sim'] - par['I0sim']),
            times, ode.model, list(alpha = par['alpha'], beta = par['beta']))
  
  temp  = data.frame(time = sim[,1], S = sim[,2], I = sim[,3], R = sim[,4], id = k)
  
  if (k == 1) {
    predictions = temp
  } else {
    predictions = rbind(predictions, temp)
  }
  
}
```

```{r}
ggplot(data_SIR[data_SIR$replicate == repl,]) +
  geom_point(mapping = aes(x = time, y = S), color = 'blue') +
  geom_point(mapping = aes(x = time, y = I), color = 'red') +
  geom_point(mapping = aes(x = time, y = R), color = 'green') +
  geom_line(data = predictions, mapping = aes(x = time, y = S, group = id), color = 'blue', alpha = 0.01) +
  geom_line(data = predictions, mapping = aes(x = time, y = I, group = id), color = 'red', alpha = 0.01) +
  geom_line(data = predictions, mapping = aes(x = time, y = R, group = id), color = 'green', alpha = 0.01)
```


```{r}
ggplot(data_SIR[data_SIR$replicate == repl,]) +
  geom_point(mapping = aes(x = time, y = S), color = 'blue') +
  geom_point(mapping = aes(x = time, y = I), color = 'red') +
  geom_point(mapping = aes(x = time, y = R), color = 'green') +
  stat_summary(data = predictions, mapping = aes(x = time, y = S),
               fun.min = function(x) quantile(x, 0.05),
               fun.max = function(x) quantile(x, 0.95),
               geom = 'ribbon', fill = 'blue', alpha = 0.5) +
  stat_summary(data = predictions, mapping = aes(x = time, y = I),
               fun.min = function(x) quantile(x, 0.05),
               fun.max = function(x) quantile(x, 0.95),
               geom = 'ribbon', fill = 'red', alpha = 0.5) +
  stat_summary(data = predictions, mapping = aes(x = time, y = R),
               fun.min = function(x) quantile(x, 0.05),
               fun.max = function(x) quantile(x, 0.95),
               geom = 'ribbon', fill = 'green', alpha = 0.5)
```

